---
title: "glasseel_gam"
author: "Tessa van der Hammen"
date: "2025-09-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
datapath  <-"data"
if(Sys.info()[["user"]] == 'hamme0055'){
  setwd("C:/Tessa/glass_eel/R")
  datawd <- file.path(getwd(),datapath)
} else if (Sys.info()[["user"]] == 'cedric.briand'){
  setwd("C:/workspace/DIASPARA_glass_eel/R")
  datawd <- file.path(getwd(),datapath)
}
```

This script analyses glass eel size from different locations in Europe. We do a seasonal gam.
{>> this is a comment from Cédric >>}

```{r Process data, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(lubridate)
library(mgcv)
library(dplyr)
library(ggplot2)
library(visreg)


# read in data
load(file = file.path(datawd, "dat.Rdata"))

don   <- dat

###
origin    <- as.numeric(as.Date(ymd(19600101)))
don$fi_date <- as.Date(don$fi_date2, format= "%Y-%m-%d")

don$yday=yday(don$fi_date) # yday is the season

don$doy=don$yday-305 # year begins in november
don$season<-paste0(year(don$fi_date)-1,"-",year(don$fi_date)) # year-1-year
don$time  <- as.numeric(as.Date(don$fi_date, format= "%Y-%m-%d")) - origin



nyears <- length(unique(don$fi_year))


```

1. make some exploratory plots with the raw data

```{r exploratory plots, echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# check for outliers
ggplot(don)+ geom_point(aes(x=fi_date, y=jitter(lengthmm)))+
  facet_wrap(~ser_nameshort, scales='free_y') +geom_smooth(aes(x=fi_date, y=jitter(lengthmm)))

ggplot(don)+ geom_point(aes(x=yday, y=jitter(lengthmm)))+
  facet_wrap(~ser_nameshort, scales='free_y') +geom_smooth(aes(x=yday, y=jitter(lengthmm)))

# make lf distribution
ggplot(don, aes(x=lengthmm)) +    
 geom_histogram(binwidth=1)+facet_wrap(~ser_nameshort, scales = "free_y")

```

Do some datacleaning. Remove american eels and dataset with very small amounts of data.Run model from 2000? before it is just Den Oever.

```{r datacleaning, include=FALSE}
# remove East_river (american eel)
#don <- don[!(don$ser_nameshort %in% 'East_River'),]

# remove datasets with little data
don <- don[!(don$ser_nameshort %in% c('BdareG', 'FealGY', 'InagG', 'MaigG', 'CorGY', 'BoyneGY','LiffGY', 'InagG', 'FealGY')),]

# remove outliers Den Oever
don <- don[!(don$ser_nameshort %in% 'RhDOG' & don$yday <75),]

# remove data before 2000?
#don <- don[dat$fi_year > 1999,]
#


```

run and check the gam model

```{r gam model}
# cr is standard cubic spline
# cc start and end at the same length (for seasonal)

don$ser_nameshort <- as.factor(don$ser_nameshort)

don1 <- don[, c("lengthmm", "ser_nameshort", "time", 'yday', 'fi_date')]
don1 <- don1[complete.cases(don1),]

g3.1 <- gam(lengthmm~ser_nameshort+s(yday,bs="cc", k=6) +
            s(time, bs = "cr", k =10),
               data=don1,
          family = gaussian)

summary(g3.1)
#gam.check(g3.1)

don1$res <- residuals(g3.1)
vis.gam(g3.1)
qq.gam(g3.1,rep=100,level=1,type="pearson",pch=19,cex=.2)

time1<-as.numeric(as.Date(ymd(20240101)))-origin

v2<-visreg(g3.1, xvar="time", cond= list(time = time1))

v1<-visreg(g3.1, xvar="yday", by= "ser_nameshort", cond= list(time = time1))
```

make plots gam model

```{r plots gam model, message=FALSE, warning=FALSE, paged.print=FALSE}

plot(g3.1, ylim=c(-10,10))

ggplot(don1) + 
  facet_wrap(~ser_nameshort, scales='free_y')+
  geom_smooth(aes(x=yday, y=res))

ggplot(don1) + 
  geom_point(aes(x=yday, y=res, color=ser_nameshort))+facet_wrap(~ser_nameshort)+
  geom_smooth(aes(x=yday, y=res))

predata <- data.frame(
  dates = rep(seq(as.Date('2000-01-01'), as.Date('2025-12-31'), by = 'days'), length(unique(don$ser_nameshort))),
  ser_nameshort = rep(unique(don$ser_nameshort), each=length(seq(as.Date('2000-01-01'), as.Date('2025-12-31'), by = 'days'))))
predata$time <- as.numeric(as.Date(predata$dates, format= "%Y-%m-%d")) - origin
predata$fi_year <- format(as.Date(predata$dates, format="%Y-%m-%d"), "%Y")
predata$yday=yday(predata$dates)
predata$fi_date <- as.Date(predata$dates, format="%Y-%m-%d")

pred <- predict(g3.1, newdata=predata,se.fit=TRUE)
predata$pred_length <- pred$fit
predata$pred_length_lwr <- pred$fit-1.96*pred$se.fit
predata$pred_length_upr <- pred$fit+1.96*pred$se.fit


ggplot(predata)+
  #geom_point(aes(x=fi_date,y=jitter(lengthmm)),col="#043C6B", data=don1)+
  geom_line(aes(x=fi_date,y=pred_length), col='red')+
  geom_ribbon(data=predata,aes(x=fi_date,ymin=pred_length_lwr,ymax=pred_length_upr, group=fi_year),alpha=0.3,fill="#BF8330")+
  theme_minimal()+
  facet_wrap(~ser_nameshort, scales='free_y')
  #ylim(0,100)


p2  <-  ggplot(predata) +
  geom_line(aes(x=yday,y=pred_length, group=fi_year, color=fi_year)) +
  theme_minimal() +
  theme(panel.border = element_blank(),
        axis.line = element_line()) +
  xlab("yday") +
  facet_wrap(~ser_nameshort)+
  ylim(63,80)
print(p2)


#plot(g3.1, rug = FALSE, se = FALSE, n2 = 80, main = "gam with t2")



```

```{r gam-specific_ge_stage}


```

```{r gam-model_DenOever}
# First select Den Oever data ------------------

donrhdo <- don |> filter(ser_nameshort == "RhDOG")
donrhdo <- donrhdo[, c("lengthmm", "ser_nameshort", "time", 'yday', 'fi_date', "season")]
donrhdo <- donrhdo[complete.cases(donrhdo),]
donrhdo$year <- year(donrhdo$fi_date)
# less samples after 2002 and a hole in the series.
donrhdo |> 
  group_by(year,yday) |> 
  summarize(n=n()) |>
ggplot() + geom_point(aes(x= year, y =yday, size = n ))


donrhdo$season <- as.factor(donrhdo$season)
g0 <- gam(lengthmm~s(yday,bs="cr", k=6) +    
             s(time, bs = "cr", k = 20),
                data=donrhdo,
           family = gaussian)
plot(g0, residuals = FALSE, se = TRUE, select = 1, ylim =c(-5,5))
plot(g0, residuals = FALSE, se = TRUE, select = 2, ylim =c(-5,5))
AIC(g0) # 433328.9 Deviance explained =  24.3% => 27.5 % if k=20
# model happy to use more DF for the interannual trend if trend is common
# hierachical structure in the gam model - A general smooth and 
g1 <- gam(lengthmm~s(yday,bs="cr", k=6) + 
            s(yday,bs="cr", k=4, by = season) +
            s(time, bs = "cr", k =20),
               data=donrhdo,
          family = gaussian)
# AIC 431793.3 lower so better deviance explained 29.2% =>31.2
nvar <- donrhdo |> distinct(season) |> nrow() + 2
# plot quickly seasonal trend
plot(g1, residuals = TRUE, se = TRUE, select = 1)

# seasonal trend ---------------
# uncomment for a quick plot
#plot(g1, residuals = FALSE, se = TRUE, select = 1, ylim =c(-5,5))
# partial = don't show the partial ressiduals on the plot (to better see the trend)
# 
t2024<-as.numeric(as.Date(ymd(20240101)))-origin
v10 <- visreg(g1, xvar="yday", rug = TRUE, partial = FALSE, cond=list(time=t2024))

# Time -------------
# uncomment for a quick plot
# plot(g1, residuals = TRUE, se = TRUE, select = nvar)


v11 <- visreg(g1, xvar="time")
# get back to dates
v11$fit$time=as.Date(v11$fit$time, origin=origin)
v11$res$time=as.Date(v11$res$time, origin=origin)

plot(v11,gg=TRUE,
        points=list(cex=1.5, pch=1),
        line=list(col="darkblue"),
        fill=list(col="darkblue",fill="deepskyblue",alpha=0.3))+ 
        scale_x_date()+ theme_bw()+xlab("Date") + ylab("Size (cm)")

# all terms (to see the trend)

# plot(g1,ylim =c(-5,5))

# this one is a bit too much... 
v12 <- visreg(g1, xvar="yday", by ="season", rug = TRUE, partial = FALSE, cond=list(time=t2024))
qq.gam(g1,rep=100,level=1,type="pearson",pch=19,cex=.2)
```


```{r gam-model_east_river}
# First select east river data ------------------
# there is data from 1996 to 2019, but not later
unique(don$ser_nameshort)
donea <- don |> filter(ser_nameshort == "East_River")

table(donea$month <- format(donea$fi_date, "%m"), donea$season)
# we remove months september, november and december in 2010-2011
donea <- donea[!(format(donea$fi_date, "%m") %in% c("09","11","12")),]
# we remove length < 40 mm and larger then 80mm
donea <- donea[!(donea$lengthmm <45) & !(donea$lengthmm >80),]

donea <- donea[, c("lengthmm", "ser_nameshort", "time", 'yday', 'fi_date', "season")]
donea <- donea[complete.cases(donea),]

# in 2010 there are samples later in the season
# from 2016 there are samples earlier in the year

donea |> 
  group_by(fi_date,yday) |> 
  summarize(n=n()) |>
ggplot() + geom_point(aes(x= fi_date, y =yday, size = n ))+
  theme(axis.text.x = element_text(angle = 45, hjust=1))

donea$season <- as.factor(donea$season)

# cr is standard cubic spline
# cc start and end at the same length (for seasonal)
g10 <- gam(lengthmm~s(yday,bs="cr", k=6) +    
            s(time, bs = "cr", k =10),
               data=donea,
          family = gaussian)
AIC(g10) # 205092.3 Deviance explained = 11.5%
summary(g10)

# season 2010-2011 differs....
# hierachical structure in the gam model - A general smooth and 
g11 <- gam(lengthmm~s(yday,bs="cr", k=6) + 
            s(yday,bs="cr", k=6, by = season) +
            s(time, bs = "cr", k =10),
               data=donea,
          family = gaussian) 
AIC(g11) # 202278.4 Deviance explained = 18.2%
summary(g11)

#nvar <- donea |> distinct(season) |> nrow() + 2
# plot quickly seasonal trend
plot(g10, residuals = TRUE, se = TRUE, select = 1)
plot(g10, residuals = FALSE, se = TRUE, select = 1)
plot(g10, residuals = FALSE, se = TRUE, select = 2)

plot(g11,ylim=c(-100,500))
plot(g11, residuals = TRUE, se = TRUE, select = 1, ylim=c(-300,1000))

plot(g11, residuals = FALSE, se = TRUE, select=1,ylim=c(-300,1000))

donea$res <- residuals(g11)
vis.gam(g10)
qq.gam(g10,rep=100,level=1,type="pearson",pch=19,cex=.2)

time1<-as.numeric(as.Date(ymd(20190101)))-origin

v10<-visreg(g10, xvar="yday", cond= list(time = time1))
v10<-visreg(g10, xvar="time", cond= list(time = time1))


v2$fit$time=as.Date(v2$fit$time, origin=as.Date(ymd(19970101)))
v2$res$time=as.Date(v2$res$time, origin=as.Date(ymd(19970101)))
v2<-visreg(g11,xvar="time")



```

